spring:
  servlet:
    multipart:
      enabled: true #是否启用http上传处理
      max-request-size: 200MB #最大请求文件的大小
      max-file-size: 200MB #设置单个文件最大长度
  datasource:
    url: jdbc:mysql://cgzh.njupt.edu.cn:3306/patent_transfer?useUnicode=true&characterEncoding=utf8&useSSL=true
    username: admin
    password: njupt@123
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  type-enums-package: com.ran.patentTransfer.enums
  configuration:
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations:  classpath:mapping/*.xml


server:
  port: 8089
  servlet:
    session:
      timeout: PT3H


#log配置
logging:
  file:
    name: ./logs/error.log
  level:
    root: error
