spring:
  servlet:
    multipart:
      enabled: true #是否启用http上传处理
      max-request-size: 200MB #最大请求文件的大小
      max-file-size: 200MB #设置单个文件最大长度
  datasource:
    url: jdbc:mysql://cgzh.njupt.edu.cn:3306/collection_pro?useUnicode=true&characterEncoding=utf8&useSSL=true
    username: admin
    password: njupt@123
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  type-enums-package: cn.njupt.njupt_patent_collection_backend.enums
  configuration:
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.njupt.njupt_patent_collection_backend.entity


server:
  port: 8089
  servlet:
    session:
      timeout: PT30M #过期时间30分钟

#log配置
logging:
  file:
    name: ./prologs/error.log
  level:
    root: error

